[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

[build]
  publish = "dist"
  command = "pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-js-obfuscator"

[plugins.inputs]
  compact = true
  simplify = true
